<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>metools</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">metools</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">metools</h1>

</div>


<style type="text/css">
h1.title{
  font-size: 52px;
  text-align:center;
}
p{
  font-size:16px;
}
h3{
  font-size:18px;
  text-align:center;
}
table{
  margin-left:auto;
  margin-right:auto;
}
td {
  padding: 0.5em;
}
.hljs-comment{
  color:blue;
}
</style>
<p><br> <br></p>
<p>This is the official guide of the metools package, its purpose is to explain the functions of the package and examples of how they can be applied correctly.<br></p>
<p>The main objective of the metools package is to facilitate the production of graphs and reports, more specifically in macroeconomic work, the functions are divided into graphics and data manipulators. <br> See below the package functions and their respective divisions: <br></p>
<h3 style="text-align=center;font-size:14px">
<strong>Data manipulation</strong>
</h3>
<table class="table" style="width: auto !important; float: right; margin-left: 10px;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
cuminyear
</td>
<td style="text-align:left;">
Accumulated variation in year
</td>
</tr>
<tr>
<td style="text-align:left;">
cuminyear_var
</td>
<td style="text-align:left;">
Accumulated variation in year to decimal data
</td>
</tr>
<tr>
<td style="text-align:left;">
cum_var
</td>
<td style="text-align:left;">
Accumulated variation
</td>
</tr>
<tr>
<td style="text-align:left;">
pct_change
</td>
<td style="text-align:left;">
Percentual change in t periods of a serie
</td>
</tr>
<tr>
<td style="text-align:left;">
num2month
</td>
<td style="text-align:left;">
Transform month names to month numbers
</td>
</tr>
<tr>
<td style="text-align:left;">
month2num
</td>
<td style="text-align:left;">
Transform month numbers to month names
</td>
</tr>
<tr>
<td style="text-align:left;">
me.lag
</td>
<td style="text-align:left;">
Lag or lead a vector, according value of t
</td>
</tr>
<tr>
<td style="text-align:left;">
me.spread
</td>
<td style="text-align:left;">
Spread an dataframe
</td>
</tr>
<tr>
<td style="text-align:left;">
stattable
</td>
<td style="text-align:left;">
Descritive statistic table
</td>
</tr>
</tbody>
</table>
<table class="table" style="width: auto !important; margin-right: 0; margin-left: auto">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
col2char
</td>
<td style="text-align:left;">
Transform defined columns to character
</td>
</tr>
<tr>
<td style="text-align:left;">
col2factor
</td>
<td style="text-align:left;">
Transform defined columns to factor
</td>
</tr>
<tr>
<td style="text-align:left;">
col2num
</td>
<td style="text-align:left;">
Transform defined columns to numeric
</td>
</tr>
<tr>
<td style="text-align:left;">
col2percent
</td>
<td style="text-align:left;">
Add percent in column
</td>
</tr>
<tr>
<td style="text-align:left;">
colpct2num
</td>
<td style="text-align:left;">
Remove percent from a column, and transform in number
</td>
</tr>
<tr>
<td style="text-align:left;">
colround
</td>
<td style="text-align:left;">
Round defined columns
</td>
</tr>
</tbody>
</table>
<table class="table" style="width: auto !important; float: left; margin-right: 10px;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
Plot
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
p.line
</td>
<td style="text-align:left;">
Line plot
</td>
</tr>
<tr>
<td style="text-align:left;">
p.col
</td>
<td style="text-align:left;">
Bar plot
</td>
</tr>
<tr>
<td style="text-align:left;">
p.col_ord
</td>
<td style="text-align:left;">
Ordered bar plot
</td>
</tr>
<tr>
<td style="text-align:left;">
p.col_ord_wl
</td>
<td style="text-align:left;">
Ordered bar plot with legend
</td>
</tr>
<tr>
<td style="text-align:left;">
p.col_wl
</td>
<td style="text-align:left;">
Bar plot with legend
</td>
</tr>
<tr>
<td style="text-align:left;">
p.tscol
</td>
<td style="text-align:left;">
Bar plot in time serie format
</td>
</tr>
<tr>
<td style="text-align:left;">
p.tsl
</td>
<td style="text-align:left;">
Line plot in time serie format
</td>
</tr>
<tr>
<td style="text-align:left;">
p.gradientcolor
</td>
<td style="text-align:left;">
Create Gradient
</td>
</tr>
<tr>
<td style="text-align:left;">
p.seqdatebreaks
</td>
<td style="text-align:left;">
Create Date Interval
</td>
</tr>
<tr>
<td style="text-align:left;">
p.colorbypositive
</td>
<td style="text-align:left;">
Color by positive or negative
</td>
</tr>
<tr>
<td style="text-align:left;">
p.colorbyvar
</td>
<td style="text-align:left;">
Color by variation
</td>
</tr>
<tr>
<td style="text-align:left;">
mp.s
</td>
<td style="text-align:left;">
Multi serie plot
</td>
</tr>
<tr>
<td style="text-align:left;">
mp.ts
</td>
<td style="text-align:left;">
Multi serie plot in time serie format
</td>
</tr>
</tbody>
</table>
<table class="table" style="width: auto !important; ">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
Graphic models
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
gm.col
</td>
<td style="text-align:left;">
Bar Graphic Model
</td>
</tr>
<tr>
<td style="text-align:left;">
gm.col_ord
</td>
<td style="text-align:left;">
Ordered Bar Graphic Model
</td>
</tr>
<tr>
<td style="text-align:left;">
gm.col_ord_wl
</td>
<td style="text-align:left;">
Ordered Bar Graphic with Legend Model
</td>
</tr>
<tr>
<td style="text-align:left;">
gm.col_wl
</td>
<td style="text-align:left;">
Bar Graphic with Legend Model
</td>
</tr>
<tr>
<td style="text-align:left;">
gm.line
</td>
<td style="text-align:left;">
Line Graphic Model
</td>
</tr>
<tr>
<td style="text-align:left;">
gm.tsl
</td>
<td style="text-align:left;">
Time serie line Graphic Model
</td>
</tr>
<tr>
<td style="text-align:left;">
gm.tscol
</td>
<td style="text-align:left;">
Time serie bar Graphic Model
</td>
</tr>
<tr>
<td style="text-align:left;">
gm.tscol2
</td>
<td style="text-align:left;">
Time serie bar Graphic Model
</td>
</tr>
</tbody>
</table>
<p style="font-size:11px;text-align:center">
<strong>Note that all functions of graphical category have a prefix,<br>the function of it is to distinguish the graphical functions<br> from the data manipulate functions.<br> In the next session we will explain each category and its function.</strong>
</p>
<p><br></p>
<p>For the application of the examples will be use a timeserie of the United States GDP, it was taken from the World Bank, for a reliable execution of the examples it is available for download clicking here. Some examples will be use codes from the preparation of this guide, due to the similarity with the preparation of a report, as it was done in R Markdown.</p>
<p><br></p>
<h2 style="text-align:center;font-size:32px">
<strong>Data manipulation functions</strong>
</h2>
<br>
<p style="margin-left:auto">
<p>The data manipulation functions do not have a defined suffix, a good part of their functions work with data.frames, a few exceptions should be worked at vector. See below each of the data manipulation functions in detail.</p>
</p>
<h3 style="font-size:22px;">
<strong>col2char</strong>
</h3>
<p>col2char function receive a data.frame object in x parameter and return a new data.frame object with the columns defined between the start and end parameter in character class.</p>
<p style="text-align:center;">
<strong>col2char(x,start,end)</strong>
<p>
<p style="text-align:center;">
x: a data.frame object<br>start: number of start column<br>end: number of end column
<p>
<p>Class transformations into data.frames can require a good number of lines of code, especially when done by beginner programmers. The col2char function serves to meet this need. Making this guide I needed to do some transformations in the data.frame of the functions table, even being a small example, it works well to demonstrate the usefulness of this function.</p>
<pre class="r"><code># Using R base function
mp_functions[[1]]=as.character(mp_functions[[1]])
mp_functions[[2]]=as.character(mp_functions[[2]])
plot_functions[[1]]=as.character(plot_functions[[1]])
plot_functions[[2]]=as.character(plot_functions[[2]])

# Using metools col2char function
mp_functions=col2char(mp_functions,start=1)
plot_functions=col2char(plot_functions,start=1)</code></pre>
<p>Using the R base function we use about four rows, to transform two columns of two data.frames, using the col2char function we reduce the number of rows of code required by half. This is very important, because often data.frames contain more than ten lines.</p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>col2factor</strong>
</h3>
<p>col2factor function receive a data.frame object in x parameter and return a new data.frame object with the columns defined between the start and end parameter in factor class.</p>
<p style="text-align:center;">
<strong>col2factor(x,start,end)</strong>
<p>
<p style="text-align:center;">
x: a data.frame object<br>start: number of start column<br>end: number of end column
<p>
<pre class="r"><code>#Transform Date column in factor.
usagdp=col2factor(usagdp,start=1,end=1)
usagdp</code></pre>
<pre><code>##         Date GDP..current.US.. GDP.growth..annual...
## 1 2010-01-01          14.99205              2.563767
## 2 2011-01-01          15.54258              1.550836
## 3 2012-01-01          16.19701              2.249546
## 4 2013-01-01          16.78485              1.842081
## 5 2014-01-01          17.52175              2.451973
## 6 2015-01-01          18.21930              2.880910
## 7 2016-01-01          18.70719              1.567215
## 8 2017-01-01          19.48539              2.217010
## 9 2018-01-01          20.54434              2.927323</code></pre>
<pre class="r"><code>#See factor levels
levels(usagdp[[1]])</code></pre>
<pre><code>## [1] &quot;2010-01-01&quot; &quot;2011-01-01&quot; &quot;2012-01-01&quot; &quot;2013-01-01&quot; &quot;2014-01-01&quot;
## [6] &quot;2015-01-01&quot; &quot;2016-01-01&quot; &quot;2017-01-01&quot; &quot;2018-01-01&quot;</code></pre>
<p><br></p>
<h3 style="font-size:22px;">
<strong>col2num</strong>
</h3>
<p>col2num function receive a data.frame object in x parameter and return a new data.frame object with the columns defined between the start and end parameter in numeric class.</p>
<p style="text-align:center;">
<strong>col2num(x,start,end)</strong>
<p>
<p style="text-align:center;">
x: a data.frame object<br>start: number of start column<br>end: number of end column
<p>
<pre class="r"><code>#Transform GDP columns in numeric.
usagdp=col2num(usagdp,start=2,end=3)
usagdp</code></pre>
<pre><code>##         Date GDP..current.US.. GDP.growth..annual...
## 1 2010-01-01          14.99205              2.563767
## 2 2011-01-01          15.54258              1.550836
## 3 2012-01-01          16.19701              2.249546
## 4 2013-01-01          16.78485              1.842081
## 5 2014-01-01          17.52175              2.451973
## 6 2015-01-01          18.21930              2.880910
## 7 2016-01-01          18.70719              1.567215
## 8 2017-01-01          19.48539              2.217010
## 9 2018-01-01          20.54434              2.927323</code></pre>
<p><br></p>
<h3 style="font-size:22px;">
<strong>col2percent</strong>
</h3>
<p>col2percent function receive a data.frame object in x parameter and return a new data.frame object with the columns defined between the start and end parameter in character class but with percent sign.</p>
<p style="text-align:center;">
<strong>col2percent(x,start,end,mult100)</strong>
<p>
<p style="text-align:center;">
x: a data.frame object<br>start: number of start column<br>end: number of end column<br>mult100: if values are in decimal form, use this to solve
<p>
<pre class="r"><code>#Transform GDP growht column in percent.
usagdp=col2percent(usagdp,start=3,end=3)
usagdp</code></pre>
<pre><code>##         Date GDP..current.US.. GDP.growth..annual...
## 1 2010-01-01          14.99205     2.56376655876581%
## 2 2011-01-01          15.54258     1.55083550568156%
## 3 2012-01-01          16.19701     2.24954585236992%
## 4 2013-01-01          16.78485     1.84208107101102%
## 5 2014-01-01          17.52175     2.45197303536034%
## 6 2015-01-01          18.21930     2.88091046605219%
## 7 2016-01-01          18.70719     1.56721516997864%
## 8 2017-01-01          19.48539     2.21701033031884%
## 9 2018-01-01          20.54434     2.92732272821085%</code></pre>
<p>If values are in decimal form, you can use the mult100 parameter, see below:</p>
<pre class="r"><code>#Transform GDP growht column in percent.
usagdp2=col2percent(usagdp,start=3,end=3,mult100=TRUE)
usagdp=cbind(usagdp,&quot;Function result&quot;=usagdp2[,3])
usagdp</code></pre>
<pre><code>##         Date GDP..current.US.. GDP.growth..annual...   Function result
## 1 2010-01-01          14.99205            0.02563767 2.56376655876581%
## 2 2011-01-01          15.54258            0.01550836 1.55083550568156%
## 3 2012-01-01          16.19701            0.02249546 2.24954585236992%
## 4 2013-01-01          16.78485            0.01842081 1.84208107101102%
## 5 2014-01-01          17.52175            0.02451973 2.45197303536034%
## 6 2015-01-01          18.21930            0.02880910 2.88091046605219%
## 7 2016-01-01          18.70719            0.01567215 1.56721516997864%
## 8 2017-01-01          19.48539            0.02217010 2.21701033031884%
## 9 2018-01-01          20.54434            0.02927323 2.92732272821085%</code></pre>
<p><br></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>colpct2num</strong>
</h3>
<p>colpct2num function receive a data.frame object in x parameter and return a new data.frame object with the columns defined between the start and end parameter in integer class, use this to transform columns with percent sign in integer or decimal.</p>
<p style="text-align:center;">
<strong>colpct2num(x,start,end,div100)</strong>
<p>
<p style="text-align:center;">
x: a data.frame object<br>start: number of start column<br>end: number of end column<br>div100: if you need result in decimal form use this.
<p>
<pre class="r"><code>#Transform GDP growht column in percent.
usagdp=colpct2num(usagdp,start=3,end=3,div100=FALSE)
usagdp</code></pre>
<pre><code>##         Date GDP..current.US.. GDP.growth..annual...
## 1 2010-01-01          14.99205              2.563767
## 2 2011-01-01          15.54258              1.550836
## 3 2012-01-01          16.19701              2.249546
## 4 2013-01-01          16.78485              1.842081
## 5 2014-01-01          17.52175              2.451973
## 6 2015-01-01          18.21930              2.880910
## 7 2016-01-01          18.70719              1.567215
## 8 2017-01-01          19.48539              2.217010
## 9 2018-01-01          20.54434              2.927323</code></pre>
<p>If values are in integer form, you can use the div100 parameter, see below:</p>
<pre class="r"><code>#Transform GDP growht column in percent.
usagdp=colpct2num(usagdp,start=3,end=3,div100=TRUE)
usagdp=cbind(usagdp,&quot;Function result&quot;=usagdp2[,3])
usagdp</code></pre>
<pre><code>##         Date GDP..current.US.. GDP.growth..annual...   Function result
## 1 2010-01-01          14.99205            0.02563767 2.56376655876581%
## 2 2011-01-01          15.54258            0.01550836 1.55083550568156%
## 3 2012-01-01          16.19701            0.02249546 2.24954585236992%
## 4 2013-01-01          16.78485            0.01842081 1.84208107101102%
## 5 2014-01-01          17.52175            0.02451973 2.45197303536034%
## 6 2015-01-01          18.21930            0.02880910 2.88091046605219%
## 7 2016-01-01          18.70719            0.01567215 1.56721516997864%
## 8 2017-01-01          19.48539            0.02217010 2.21701033031884%
## 9 2018-01-01          20.54434            0.02927323 2.92732272821085%</code></pre>
<p><br></p>
<h3 style="font-size:22px;">
<strong>colround</strong>
</h3>
<p>colround function receive a data.frame object in x parameter and return a new data.frame object with the columns defined between the start and end parameter rounded. To summarize, this function round columns.</p>
<p style="text-align:center;">
<strong>colround(x,start,end,div100)</strong>
<p>
<p style="text-align:center;">
x: a data.frame object<br>start: number of start column<br>end: number of end column<br>digits: number of digits
<p>
<pre class="r"><code>#Round GDP columns
usagdp=colround(usagdp,start=2,end=3,digits=2)
usagdp</code></pre>
<pre><code>##         Date GDP..current.US.. GDP.growth..annual...
## 1 2010-01-01             14.99                  2.56
## 2 2011-01-01             15.54                  1.55
## 3 2012-01-01             16.20                  2.25
## 4 2013-01-01             16.78                  1.84
## 5 2014-01-01             17.52                  2.45
## 6 2015-01-01             18.22                  2.88
## 7 2016-01-01             18.71                  1.57
## 8 2017-01-01             19.49                  2.22
## 9 2018-01-01             20.54                  2.93</code></pre>
<p><br></p>
<h3 style="font-size:22px;">
<strong>cuminyear</strong>
</h3>
<p>cuminyear calculates an accumulated variation in year of a index. Data must be start in january, use start to set this, if you data don’t start in january and you need use this values, consider complete the previous months with 0.</p>
<p style="text-align:center;">
<strong>cuminyear(data,coldate,colnum,start)</strong>
<p>
<p style="text-align:center;">
data: a data.frame object<br>coldate: number of date column<br>colnum: number of values column<br>start: number of start row
<p>
<pre class="r"><code>randomts=data.frame(&quot;Date&quot;=as.Date(seq.Date(as.Date(&#39;2019-01-01&#39;),as.Date(&#39;2019-12-01&#39;),&#39;month&#39;)),
            &quot;Values&quot;=c(100,110,105,115,118,95,92,100,108,105,110,112)) #Creating a random time serie

cuminyear(randomts,coldate = 1,colnum=2,start=1)</code></pre>
<pre><code>##  [1]  0.00  0.10  0.05  0.15  0.18 -0.05 -0.08  0.00  0.08  0.05  0.10  0.12</code></pre>
<p>As previously mentioned, the data must be start in january, see below examples of how to solve this problem.</p>
<pre class="r"><code>randomts=data.frame(&quot;Date&quot;=as.Date(seq.Date(as.Date(&#39;2019-04-01&#39;),as.Date(&#39;2019-12-01&#39;),&#39;month&#39;)),
            &quot;Values&quot;=c(115,118,95,92,100,108,105,110,112)) #Creating a random time serie

# How we can see, data don&#39;t start in january, we have two ways to solve this:
# first -&gt; complete data with first value:
randomts=merge.data.frame(x=data.frame(&quot;Date&quot;=as.Date(seq.Date(as.Date(&#39;2019-01-01&#39;),as.Date(&#39;2019-03-01&#39;),&#39;month&#39;)),&quot;Values&quot;=rep(randomts[1,2])),y=randomts,all = T)
cuminyear(randomts,coldate = 1,colnum=2,start=1)</code></pre>
<pre><code>##  [1]  0.00000000  0.00000000  0.00000000  0.00000000  0.02608696 -0.17391304
##  [7] -0.20000000 -0.13043478 -0.06086957 -0.08695652 -0.04347826 -0.02608696</code></pre>
<pre class="r"><code># second -&gt; using start parameter to define row to start
# In this case we need a more one year in data, lets create a new time serie.
randomts=data.frame(&quot;Date&quot;=as.Date(seq.Date(as.Date(&#39;2018-09-01&#39;),as.Date(&#39;2019-12-01&#39;),&#39;month&#39;)),
            &quot;Values&quot;=c(100,102,96,98,100,110,105,115,118,95,92,100,108,105,110,112))
#now we can start in third line, in 2019 january.
cuminyear(randomts,coldate = 1,colnum=2,start=5)</code></pre>
<pre><code>##  [1]    NA    NA    NA    NA  0.00  0.10  0.05  0.15  0.18 -0.05 -0.08  0.00
## [13]  0.08  0.05  0.10  0.12</code></pre>
<p><br></p>
<h3 style="font-size:22px;">
<strong>cuminyear_var</strong>
</h3>
<p>cuminyear_var calculates an accumulated variation in year of a rate, _var means the data must be a percentage variation. Data must be start in january, if you data don’t start in january and you need use this values, consider complete the previous months with 0.</p>
<p style="text-align:center;">
<strong>cuminyear_var(data,coldate,colnum,start)</strong>
<p>
<p style="text-align:center;">
data: a data.frame object<br>coldate: number of date column<br>colnum: number of values column<br>div100: if data percent are in integer representation, use this
<p>
<pre class="r"><code>randomts=data.frame(&quot;Date&quot;=as.Date(seq.Date(as.Date(&#39;2019-01-01&#39;),as.Date(&#39;2019-12-01&#39;),&#39;month&#39;)),
            &quot;Values&quot;=c(0.02,0.06,0.04,-0.06,-0.02,0.01,-0.06,0.03,0.08,0.01,0.05,0.03))

cuminyear_var(randomts,coldate = 1,colnum = 2)</code></pre>
<pre><code>##         Values
## 1   0.02000000
## 2   0.08120000
## 3   0.12444800
## 4   0.05698112
## 5   0.03584150
## 6   0.04619991
## 7  -0.01657208
## 8   0.01293076
## 9   0.09396522
## 10  0.10490487
## 11  0.16015011
## 12  0.19495461</code></pre>
<p>As previously mentioned, the data must be start in january, see below examples of how to solve this problem.</p>
<pre class="r"><code>randomts=data.frame(&quot;Date&quot;=as.Date(seq.Date(as.Date(&#39;2019-04-01&#39;),as.Date(&#39;2019-12-01&#39;),&#39;month&#39;)),
            &quot;Values&quot;=c(-0.06,-0.02,0.01,-0.06,0.03,0.08,0.01,0.05,0.03))
randomts</code></pre>
<pre><code>##         Date Values
## 1 2019-04-01  -0.06
## 2 2019-05-01  -0.02
## 3 2019-06-01   0.01
## 4 2019-07-01  -0.06
## 5 2019-08-01   0.03
## 6 2019-09-01   0.08
## 7 2019-10-01   0.01
## 8 2019-11-01   0.05
## 9 2019-12-01   0.03</code></pre>
<pre class="r"><code># How we can see, data don&#39;t start in january,to solve this we can complete data with 0.
randomts=merge.data.frame(x=data.frame(&quot;Date&quot;=as.Date(seq.Date(as.Date(&#39;2019-01-01&#39;),as.Date(&#39;2019-03-01&#39;),&#39;month&#39;)),&quot;Values&quot;=rep(0)),y=randomts,all = T)
cuminyear_var(randomts,coldate = 1,colnum=2)</code></pre>
<pre><code>##         Values
## 1   0.00000000
## 2   0.00000000
## 3   0.00000000
## 4  -0.06000000
## 5  -0.07880000
## 6  -0.06958800
## 7  -0.12541272
## 8  -0.09917510
## 9  -0.02710911
## 10 -0.01738020
## 11  0.03175079
## 12  0.06270331</code></pre>
<p>If your data are in integer representation, div100 parameter must be TRUE to correct results. See the div100 parameter used in below example.</p>
<pre class="r"><code>randomts=data.frame(&quot;Date&quot;=as.Date(seq.Date(as.Date(&#39;2019-01-01&#39;),as.Date(&#39;2019-12-01&#39;),&#39;month&#39;)),
            &quot;Values&quot;=c(2,6,4,-6,-2,1,-6,3,8,1,5,3))
cuminyear_var(randomts,coldate = 1,colnum=2,div100=T)</code></pre>
<pre><code>##         Values
## 1   0.02000000
## 2   0.08120000
## 3   0.12444800
## 4   0.05698112
## 5   0.03584150
## 6   0.04619991
## 7  -0.01657208
## 8   0.01293076
## 9   0.09396522
## 10  0.10490487
## 11  0.16015011
## 12  0.19495461</code></pre>
<p><br></p>
<h3 style="font-size:22px;">
<strong>cum_var</strong>
</h3>
<p>cum_var calculates an accumulated variation of a rate during a certain period of time, _var means the data must be a percentage variation.</p>
<p style="text-align:center;">
<strong>cum_var(data,colnum,t,div100=F)</strong>
<p>
<p style="text-align:center;">
data: a data.frame object<br>colnum: number of values column<br>t: number of times to acummulate<br>div100: if data percent are in integer representation, use this
<p>
<pre class="r"><code>randomts=data.frame(&quot;Date&quot;=as.Date(seq.Date(as.Date(&#39;2019-01-01&#39;),as.Date(&#39;2019-12-01&#39;),&#39;month&#39;)),
            &quot;Values&quot;=c(0.02,0.06,0.04,-0.06,-0.02,0.01,-0.06,0.03,0.08,0.01,0.05,0.03))
cum_var(randomts,colnum=2,t=3,div100=F)</code></pre>
<pre><code>##       Values
## 1         NA
## 2         NA
## 3   0.124448
## 4   0.036256
## 5  -0.041952
## 6  -0.069588
## 7  -0.069588
## 8  -0.022118
## 9   0.045656
## 10  0.123524
## 11  0.145340
## 12  0.092315</code></pre>
<p>If your data are in integer representation, div100 parameter must be TRUE to correct results. See the div100 parameter used in below example.</p>
<pre class="r"><code>randomts=data.frame(&quot;Date&quot;=as.Date(seq.Date(as.Date(&#39;2019-01-01&#39;),as.Date(&#39;2019-12-01&#39;),&#39;month&#39;)),
            &quot;Values&quot;=c(2,6,4,-6,-2,1,-6,3,8,1,5,3))
cum_var(randomts,colnum=2,t=3,div100=T)</code></pre>
<pre><code>##       Values
## 1         NA
## 2         NA
## 3   0.124448
## 4   0.036256
## 5  -0.041952
## 6  -0.069588
## 7  -0.069588
## 8  -0.022118
## 9   0.045656
## 10  0.123524
## 11  0.145340
## 12  0.092315</code></pre>
<p><br></p>
<h3 style="font-size:22px;">
<strong>pct_change</strong>
</h3>
<p>pct_change calculate the percentual change in t periods of a serie. We can use this function to calculate the acumulated variation of an index, for example to calculate the accumulated variation in 12 months just set t parameter to 12.</p>
<p style="text-align:center;">
<strong>pct_change(data,colnum,t,nafill)</strong>
<p>
<p style="text-align:center;">
data: a data.frame object<br>colnum: number of values column<br>t: number of periods to accumulate<br>nafill: set value to fill NA’s before first t value
<p>
<pre class="r"><code>pct_change(usagdp,colnum=2,t=3)</code></pre>
<pre><code>##   GDP..current.US..
## 1                NA
## 2                NA
## 3                NA
## 4         0.1195831
## 5         0.1273383
## 6         0.1248558
## 7         0.1145282
## 8         0.1120692
## 9         0.1276145</code></pre>
<p><br></p>
<h3 style="font-size:22px;">
<strong>num2month</strong>
</h3>
<p>num2month transform month numbers to month names.</p>
<p style="text-align:center;">
<strong>num2month(date,abbreviate,ptbr)</strong>
<p>
<p style="text-align:center;">
date: a month numbers vector<br>abbreviate: abbreviate months name in result<br>ptbr: translate result to “Português (Brasil)”<br>
<p>
<pre class="r"><code>randomts=data.frame(&quot;Month&quot;=seq(from=1,to=12,by=1),
            &quot;Values&quot;=c(0.02,0.06,0.04,-0.06,-0.02,0.01,-0.06,0.03,0.08,0.01,0.05,0.03))
num2month(randomts[[1]])</code></pre>
<pre><code>##  [1] &quot;january&quot;   &quot;february&quot;  &quot;march&quot;     &quot;april&quot;     &quot;may&quot;       &quot;june&quot;     
##  [7] &quot;july&quot;      &quot;august&quot;    &quot;september&quot; &quot;october&quot;   &quot;november&quot;  &quot;december&quot;</code></pre>
<p>Using abbreviate function and replacing in data.frame we have:</p>
<pre class="r"><code>randomts[[1]]=num2month(randomts[[1]],abbreviate=TRUE)
randomts</code></pre>
<pre><code>##    Month Values
## 1    jan   0.02
## 2    feb   0.06
## 3    mar   0.04
## 4    apr  -0.06
## 5    may  -0.02
## 6    jun   0.01
## 7    jul  -0.06
## 8    aug   0.03
## 9    sep   0.08
## 10   oct   0.01
## 11   nov   0.05
## 12   dec   0.03</code></pre>
<p><br></p>
<h3 style="font-size:22px;">
<strong>month2num</strong>
</h3>
<p>month2num transform month names to month numbers.</p>
<p style="text-align:center;">
<strong>month2num</strong>
<p>
<p style="text-align:center;">
date: a month names vector<br>
<p>
<pre class="r"><code>randomts=data.frame(&quot;Month&quot;=c(&quot;january&quot;,&quot;february&quot;,&quot;march&quot;,&quot;april&quot;,&quot;may&quot;,&quot;june&quot;,&quot;july&quot;,&quot;august&quot;,&quot;september&quot;,
                              &quot;october&quot;,&quot;november&quot;,&quot;december&quot;),
            &quot;Values&quot;=c(0.02,0.06,0.04,-0.06,-0.02,0.01,-0.06,0.03,0.08,0.01,0.05,0.03))
month2num(randomts[[1]])</code></pre>
<pre><code>##  [1] &quot;01&quot; &quot;02&quot; &quot;03&quot; &quot;04&quot; &quot;05&quot; &quot;06&quot; &quot;07&quot; &quot;08&quot; &quot;09&quot; &quot;10&quot; &quot;11&quot; &quot;12&quot;</code></pre>
<p>Is possible abbreviate months name.</p>
<pre class="r"><code>randomts=data.frame(&quot;Month&quot;=c(&quot;jan&quot;,&quot;feb&quot;,&quot;mar&quot;,&quot;apr&quot;,&quot;may&quot;,&quot;jun&quot;,&quot;jul&quot;,&quot;aug&quot;,&quot;sep&quot;,
                              &quot;oct&quot;,&quot;nov&quot;,&quot;dec&quot;),
            &quot;Values&quot;=c(0.02,0.06,0.04,-0.06,-0.02,0.01,-0.06,0.03,0.08,0.01,0.05,0.03))
month2num(randomts[[1]])</code></pre>
<pre><code>##  [1] &quot;01&quot; &quot;02&quot; &quot;03&quot; &quot;04&quot; &quot;05&quot; &quot;06&quot; &quot;07&quot; &quot;08&quot; &quot;09&quot; &quot;10&quot; &quot;11&quot; &quot;12&quot;</code></pre>
<p><br></p>
<h3 style="font-size:22px;">
<strong>me.lag</strong>
</h3>
<p>me.lag lag a vector if t&gt;0 or lead a vector if t&lt;0.</p>
<p style="text-align:center;">
<strong>me.lag</strong>
<p>
<p style="text-align:center;">
x: a vector<br> t: number of times to lag (default=1)<br> nafill: value to fill NA’s before first t value<br> extrapolate: if TRUE, extrapolate excedent values, only if t&gt;0
</p>
<pre class="r"><code>#basic lag usage
me.lag(usagdp[[2]],t=3)</code></pre>
<pre><code>## [1]       NA       NA       NA 14.99205 15.54258 16.19701 16.78485 17.52175
## [9] 18.21930</code></pre>
<pre class="r"><code>#lag with extrapolate
me.lag(usagdp[[2]],t=3,extrapolate = TRUE)</code></pre>
<pre><code>##  [1]       NA       NA       NA 14.99205 15.54258 16.19701 16.78485 17.52175
##  [9] 18.21930 18.70719 19.48539 20.54434</code></pre>
<pre class="r"><code>#lead with me.lag
me.lag(usagdp[[2]],t=-3)</code></pre>
<pre><code>## [1] 16.78485 17.52175 18.21930 18.70719 19.48539 20.54434       NA       NA
## [9]       NA</code></pre>
<p><br></p>
<h3 style="font-size:22px;">
<strong>me.spread</strong>
</h3>
<p>me.spread transforms columns into rows and rows into columns.</p>
<p style="text-align:center;">
<strong>me.spread</strong>
<p>
<p style="text-align:center;">
data: a data frame<br> namenc: name of new column<br>mode: if results are incorretly try set this to TRUE
<p>
<p>Preparing this document I needed to extract the usdgpd time series for the World Bank website, but the data should be prepared for a better explanation. In the process, after the variable filter step, the data were organized in a long format, see below:</p>
<pre><code>##             Series name 2010-01-01 2011-01-01 2012-01-01 2013-01-01 2014-01-01
## 1     GDP (current US$)  14.992053  15.542581  16.197007  16.784849  17.521747
## 2 GDP growth (annual %)   2.563767   1.550836   2.249546   1.842081   2.451973</code></pre>
<p>The me.spread functions can solve this problem. See how use the function and the result:</p>
<pre class="r"><code>me.spread(usagdp_old)</code></pre>
<pre><code>##              GDP (current US$) GDP growth (annual %)
## 1 2010-01-01      14.992052727      2.56376655876581
## 2 2011-01-01      15.542581104      1.55083550568156
## 3 2012-01-01      16.197007349      2.24954585236992
## 4 2013-01-01       16.78484919      1.84208107101102
## 5 2014-01-01      17.521746534      2.45197303536034</code></pre>
<p>If you want to turn back to the long mode just use the function again.</p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>stattable</strong>
</h3>
<p>stattable make a descritive statistic table.</p>
<p style="text-align:center;">
<strong>stattable</strong>
<p>
<p style="text-align:center;">
data: a data frame<br> horiz: if TRUE,data.frame come horizontal<br>mode: if results are incorretly try set this to TRUE
<p>
<p>If your data is a time serie, don’t use date column in data parameter, to do this use brackets ([row,column]) like in example below.</p>
<pre class="r"><code>stattable(usagdp[,2:3])</code></pre>
<pre><code>## # A tibble: 6 x 3
##   Statistic GDP..current.US.. GDP.growth..annual...
##   &lt;chr&gt;                 &lt;dbl&gt;                 &lt;dbl&gt;
## 1 &quot;Min.   &quot;              15.0                  1.55
## 2 &quot;1st Qu.&quot;              16.2                  1.84
## 3 &quot;Median &quot;              17.5                  2.25
## 4 &quot;Mean   &quot;              17.6                  2.25
## 5 &quot;3rd Qu.&quot;              18.7                  2.56
## 6 &quot;Max.   &quot;              20.5                  2.93</code></pre>
<p><br></p>
<p><br></p>
<h2 style="text-align:center;font-size:32px">
<strong>Graphic models functions</strong>
</h2>
<br>
<p style="margin-left:auto">
<p>Graphic models function family do graphic creation easy, is recommended for new programers, they have less and easyful parameters then p.functions but the graphic customize is more limited. The simplest way to create graphs with the metools package are using the graph template functions, these functions use the plot functions (from metools) to get simplified arguments, using these functions we will have an easier but more limited creation of graphics.</p>
</p>
<h3 style="font-size:22px;">
<strong>gm.col</strong>
</h3>
<p>gm.col make a bar plot.</p>
<p style="text-align:center;">
<strong>gm.col</strong>
<p>
<p style="text-align:center;">
data :a dataframe<br> ncolx: number of x column in data frame<br> ncoly: number of y column in data frame<br> ntimes: number of observations to plot (count by tail)<br> title:title of plot<br> xlab: x axis label<br> ylab: y axis label<br> div100: If data percent are not in decimal format set TRUE.<br> percent: If TRUE, y axis in percent<br> fontsize: change size of all words in graphic (only numbers)<br> cserie: change color of serie<br> clines: color of lines in graphic<br> ctext: color of words in graphic<br> cbackground: color of graphic background<br> cbserie: color of serie border
<p>
<pre class="r"><code>randoms=data.frame(&quot;Period&quot;=letters[1:12],
            &quot;Values&quot;=c(2,6,4,-6,-2,1,-6,3,8,1,5,3))

gm.col(randoms,ncolx = 1,ncoly = 2,ntimes = 8,title = &quot;Metools - gm.col&quot;,xlab = NULL,ylab = NULL)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-33-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>gm.col_ord</strong>
</h3>
<p>gm.col_ord make a ordered bar plot.</p>
<p style="text-align:center;">
<strong>gm.col</strong>
<p>
<p style="text-align:center;">
data :a dataframe<br> ncolx: number of x column in data frame<br> ncoly: number of y column in data frame<br> ntimes: number of observations to plot (count by tail)<br> title:title of plot<br> xlab: x axis label<br> ylab: y axis label<br> percent: If TRUE, y axis in percent<br> div100: If data percent are not in decimal format set TRUE.<br> dec: If TRUE, bars plot in decrescent order. fontsize: change size of all words in graphic (only numbers)<br> cserie: change color of serie<br> clines: color of lines in graphic<br> ctext: color of words in graphic<br> cbackground: color of graphic background<br> cbserie: color of serie border
<p>
<pre class="r"><code>randoms=data.frame(&quot;Period&quot;=letters[1:12],
            &quot;Values&quot;=c(2,6,4,-6,-2,1,-6,3,8,1,5,3))

gm.col_ord(randoms,ncolx = 1,ncoly = 2,ntimes = 8,title = &quot;Metools - gm.col_ord&quot;,xlab = NULL,ylab = NULL,cserie = &#39;yellow&#39;)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-34-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Using dec argumente we have:</p>
<pre class="r"><code>gm.col_ord(randoms,ncolx = 1,ncoly = 2,ntimes = 8,title = &quot;Metools - gm.col_ord&quot;,xlab = NULL,ylab = NULL,cserie = &#39;yellow&#39;,dec=TRUE)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-35-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>gm.col_ord_wl</strong>
</h3>
<p>gm.col_ord_wl make a orderer bar plot with legend.</p>
<p style="text-align:center;">
<strong>gm.col</strong>
<p>
<p style="text-align:center;">
data :a dataframe<br> ncolx: number of x column in data frame<br> ncoly: number of y column in data frame<br> ntimes: number of observations to plot (count by tail)<br> title:title of plot<br> legtitle: title of legend<br> xlab: x axis label<br> ylab: y axis label<br> dec: If TRUE, bars plot in decrescent order.<br> div100: If data percent are not in decimal format set TRUE.<br> percent: If TRUE, y axis in percent<br> fontsize: change size of all words in graphic (only numbers)<br> colors: colors of bars (a vector with the colors of each bar)<br> clines: color of lines in graphic<br> ctext: color of words in graphic<br> cbackground: color of graphic background<br> cbserie: color of serie border<br> legwpos: legend words position (numeric)<br> legheight: height of legend box
<p>
<pre class="r"><code>randoms=data.frame(&quot;Period&quot;=letters[1:12],
            &quot;Values&quot;=c(2,6,4,-6,-2,1,-6,3,8,1,5,3))

gm.col_ord_wl(randoms,ncolx = 1,ncoly = 2,ntimes = 5,title = &quot;Metools - gm.col_ord_wl&quot;,legtitle = NULL,xlab = NULL,ylab = NULL,legwpos = -2.5)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-36-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>gm.col_wl</strong>
</h3>
<p>gm.col_wl make a bar plot with legend.</p>
<p style="text-align:center;">
<strong>gm.col</strong>
<p>
<p style="text-align:center;">
data :a dataframe<br> ncolx: number of x column in data frame<br> ncoly: number of y column in data frame<br> ntimes: number of observations to plot (count by tail)<br> title:title of plot<br> legtitle: title of legend<br> xlab: x axis label<br> ylab: y axis label<br> div100: If data percent are not in decimal format set TRUE.<br> percent: If TRUE, y axis in percent<br> fontsize: change size of all words in graphic (only numbers)<br> colors: colors of bars (a vector with the colors of each bar)<br> clines: color of lines in graphic<br> ctext: color of words in graphic<br> cbackground: color of graphic background<br> cbserie: color of serie border<br> legwpos: legend words position (numeric)<br> legheight: height of legend box
<p>
<pre class="r"><code>randoms=data.frame(&quot;Period&quot;=letters[1:12],
            &quot;Values&quot;=c(2,6,4,-6,-2,1,-6,3,8,1,5,3))

gm.col_wl(randoms,ncolx = 1,ncoly = 2,ntimes = 5,title = &quot;Metools - gm.col_wl&quot;,legtitle = NULL,xlab = NULL,ylab = NULL,legwpos = -2.5)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-37-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>gm.tscol</strong>
</h3>
<p>gm.tscol make a bar plot in time serie format. . The data don’t need be a ts object.</p>
<p style="text-align:center;">
<strong>gm.tscol</strong>
<p>
<p style="text-align:center;">
data :a dataframe<br> ncolx: number of x column in data frame<br> ncoly: number of y column in data frame<br> ntimes: number of observations to plot (count by tail)<br> title:title of plot<br> ylab: y axis label<br> percent: If TRUE, y axis in percent<br> div100: If data percent are not in decimal format set TRUE.<br> fontsize: change size of all words in graphic (only numbers)<br> datebreaks: datebreaks in x axis (default=“1 month”)<br> dateformat: format of date in x axis (need a dataformat string) (default =“%Y-%m”)<br> clines: color of lines in graphic<br> ctext: color of words in graphic<br> cbackground: color of graphic background<br> cbserie: color of serie border<br>
<p>
<pre class="r"><code>gm.tscol(usagdp,ncolx = 1,ncoly = 3,ntimes=12,title = &quot;Metools - gm.tscol&quot;,datebreaks = &quot;1 year&quot;,ylab = NULL,percent = TRUE,div100 = TRUE)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-38-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>gm.tscol2</strong>
</h3>
<p>gm.tscol2 make a bar plot in time serie format, the difference in tscol2 is that you can choose the color of serie.The data don’t need be a ts object.</p>
<p style="text-align:center;">
<strong>gm.tscol2</strong>
<p>
<p style="text-align:center;">
data :a dataframe<br> ncolx: number of x column in data frame<br> ncoly: number of y column in data frame<br> ntimes: number of observations to plot (count by tail)<br> title:title of plot<br> ylab: y axis label<br> percent: If TRUE, y axis in percent<br> div100: If data percent are not in decimal format set TRUE.<br> fontsize: change size of all words in graphic (only numbers)<br> datebreaks: datebreaks in x axis (default=“1 month”)<br> dateformat: format of date in x axis (need a dataformat string) (default =“%Y-%m”)<br> cserie: color of serie<br> clines: color of lines in graphic<br> ctext: color of words in graphic<br> cbackground: color of graphic background<br> cbserie: color of serie border<br>
<p>
<pre class="r"><code>gm.tscol2(usagdp,ncolx = 1,ncoly = 3,ntimes=12,title = &quot;Metools - gm.tscol2&quot;,datebreaks = &quot;1 year&quot;,ylab = NULL,percent = TRUE,div100 = TRUE,cserie=&quot;orange&quot;)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-39-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>gm.line</strong>
</h3>
<p>gm.line make a line plot.</p>
<p style="text-align:center;">
<strong>gm.line</strong>
<p>
<p style="text-align:center;">
data :a dataframe<br> ncolx: number of x column in data frame<br> ncoly: number of y column in data frame<br> ntimes: number of observations to plot (count by tail)<br> title:title of plot<br> xlab: x axis label<br> ylab: y axis label<br> div100: If data percent are not in decimal format set TRUE.<br> percent: If TRUE, y axis in percent<br> fontsize: change size of all words in graphic (only numbers)<br> lwdserie: size of serie<br> cserie: color of serie<br> clines: color of lines in graphic<br> ctext: color of words in graphic<br> cbackground: color of graphic background<br>
<p>
<pre class="r"><code>gm.line(usagdp,ncolx = 1,ncoly = 2,ntimes=12,title = &quot;Metools - gm.line&quot;,xlab=NULL,ylab = NULL)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-40-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>gm.tsl</strong>
</h3>
<p>gm.tsl make a line plot.</p>
<p style="text-align:center;">
<strong>gm.tsl</strong>
<p>
<p style="text-align:center;">
data :a dataframe<br> ncolx: number of x column in data frame<br> ncoly: number of y column in data frame<br> ntimes: number of observations to plot (count by tail)<br> title:title of plot<br> ylab: y axis label<br> percent: If TRUE, y axis in percent<br> div100: If data percent are not in decimal format set TRUE.<br> fontsize: change size of all words in graphic (only numbers)<br> lwdserie: size of serie<br> datebreaks: datebreaks in x axis (default=“1 month”)<br> dateformat: format of date in x axis (need a dataformat string) (default =“%Y-%m”)<br> cserie: color of serie<br> clines: color of lines in graphic<br> ctext: color of words in graphic<br> cbackground: color of graphic background<br>
<p>
<pre class="r"><code>gm.tsl(usagdp,ncolx = 1,ncoly = 3,ntimes=12,title = &quot;Metools - gm.tsl&quot;,ylab = NULL,percent = TRUE, div100= TRUE,datebreaks = &quot;1 year&quot;,dateformat = &quot;%Y&quot;,lwdserie = 2)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-41-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<p><br></p>
<h2 style="text-align:center;font-size:32px">
<strong>Plot functions</strong>
</h2>
<br>
<p style="margin-left:auto">
<p>The plot functions are the most complete way to make graphs using metools package, they have a significant amount of parameters for a better and more detailed customization of the graphs. Its functions start with the prefix p, these include one serie plot and some tools with colors and values for the axes. To plot more one serie, in plot functions have a multi plot functions, they have prefix mp.</p>
</p>
<h3 style="font-size:22px;">
<strong>p.line</strong>
</h3>
<p>p.line make a line plot.</p>
<p style="text-align:center;">
<strong>p.line</strong>
<p>
<p style="text-align:center;">
data: a dataframe<br> xaxis: x axis data<br> yaxis: y axis data<br> ybreaks: number of y axis breaks (default=10)<br> percent: If TRUE y axis in percent (default=F)<br> yaccuracy: a round for y axis (default=0.01)<br> ydecimalmark: y decimal mark (default=“.”)<br> title: title of plot<br> xlab: x axis label<br> ylab: y axis label<br> stitle: subtitle<br> note: note<br> ctitles: color of titles (title,xlab,ylab)<br> cscales: color of the scales (default= same ctitles)<br> cbgrid: color of grid background<br> clgrid: color of grid lines<br> cplot: color of plot background<br> cserie: color of serie<br> cticks: color of axis ticks<br> lwdserie: size of serie<br> pnote: position of note (default=1) (only numbers)<br> cbord: color of plot border (default= same cplot)<br> titlesize: size of title (default=20) (only numbers)<br> wordssize: size of words (default=12) (only numbers)<br> snote: size of note (default=11) (only numbers)<br> xlim: limit of x axis (default=NULL)
<p>
<pre class="r"><code>randoms=data.frame(&quot;Period&quot;=letters[1:12],
            &quot;Values&quot;=c(2,6,4,-6,-2,1,-6,3,8,1,5,3))

p.line(randoms,randoms[[1]],randoms[[2]],title = &quot;Metools - p.line&quot;,xlab = NULL,ylab = NULL,note=&quot;With p. functions we can add note&quot;)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-42-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>p.col</strong>
</h3>
<p>p.col make a bar plot.</p>
<p style="text-align:center;">
<strong>p.col</strong>
<p>
<p style="text-align:center;">
data: a dataframe<br> xaxis: x axis data<br> yaxis: y axis data<br> ybreaks: number of y axis breaks (default=10)<br> percent: If TRUE y axis in percent (default=F)<br> yaccuracy: a round for y axis (default=0.01)<br> ydecimalmark: y decimal mark (default=“.”)<br> title: title of plot<br> xlab: x axis label<br> ylab: y axis label<br> stitle: subtitle<br> note: note<br> ctitles: color of titles (title,xlab,ylab)<br> cscales: color of the scales (default= same ctitles)<br> cbgrid: color of grid background<br> clgrid: color of grid lines<br> cplot: color of plot background<br> cserie: color of serie<br> cbserie: color of serie border (default= same cserie)<br> cticks: color of axis ticks<br> lwdserie: size of serie<br> pnote: position of note (default=1) (only numbers)<br> cbord: color of plot border (default= same cplot)<br> titlesize: size of title (default=20) (only numbers)<br> wordssize: size of words (default=12) (only numbers)<br> snote: size of note (default=11) (only numbers)<br> xlim: limit of x axis (default=NULL)
<p>
<pre class="r"><code>randoms=data.frame(&quot;Period&quot;=letters[1:12],
            &quot;Values&quot;=c(2,6,4,-6,-2,1,-6,3,8,1,5,3))

p.line(randoms,randoms[[1]],randoms[[2]],title = &quot;Metools - p.col&quot;,xlab = NULL,ylab = NULL,cscales=&quot;blue&quot;,note=&quot;With p. functions we have a powerful customize &quot;)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-43-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>p.col_ord</strong>
</h3>
<p>p.col_ord make a ordered bar plot.</p>
<p style="text-align:center;">
<strong>p.col_ord</strong>
<p>
<p style="text-align:center;">
data: a dataframe<br> xaxis: x axis data<br> yaxis: y axis data<br> ybreaks: number of y axis breaks (default=10)<br> dec: if TRUE, serie come be decrescent, if FALSE crescent (default=FALSE)<br> percent: If TRUE y axis in percent (default=F)<br> yaccuracy: a round for y axis (default=0.01)<br> ydecimalmark: y decimal mark (default=“.”)<br> title: title of plot<br> xlab: x axis label<br> ylab: y axis label<br> stitle: subtitle<br> note: note<br> ctitles: color of titles (title,xlab,ylab)<br> cscales: color of the scales (default= same ctitles)<br> cbgrid: color of grid background<br> clgrid: color of grid lines<br> cplot: color of plot background<br> cserie: color of serie<br> cbserie: color of serie border (default= same cserie)<br> cticks: color of axis ticks<br> lwdserie: size of serie<br> pnote: position of note (default=1) (only numbers)<br> cbord: color of plot border (default= same cplot)<br> titlesize: size of title (default=20) (only numbers)<br> wordssize: size of words (default=12) (only numbers)<br> snote: size of note (default=11) (only numbers)<br> xlim: limit of x axis (default=NULL)
<p>
<pre class="r"><code>randoms=data.frame(&quot;Period&quot;=letters[1:12],
            &quot;Values&quot;=c(2,6,4,-6,-2,1,-6,3,8,1,5,3))

p.col_ord(randoms,randoms[[1]],randoms[[2]],title = &quot;Metools - p.col_ord&quot;,xlab = NULL,ylab = NULL,cbserie=&#39;blue&#39;)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-44-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>p.col_ord_wl</strong>
</h3>
<p>p.col_ord_wl make a ordered bar plot with legend.</p>
<p style="text-align:center;">
<strong>p.col_ord_wl</strong>
<p>
<p style="text-align:center;">
data: a dataframe<br> xaxis: x axis data<br> yaxis: y axis data<br> ybreaks: number of y axis breaks (default=10)<br> percent: If TRUE y axis in percent (default=F)<br> dec: if TRUE, serie come be decrescent, if FALSE crescent (default=FALSE)<br> yaccuracy: a round for y axis (default=0.01)<br> ydecimalmark: y decimal mark (default=“.”)<br> title: title of plot<br> xlab: x axis label<br> ylab: y axis label<br> stitle: subtitle<br> note: note<br> ctitles: color of titles (title,xlab,ylab)<br> cscales: color of the scales (default= same ctitles)<br> cbgrid: color of grid background<br> clgrid: color of grid lines<br> cplot: color of plot background<br> cbserie: color of serie border (default= same cserie)<br> cticks: color of axis ticks<br> lwdserie: size of serie<br> legtitle: title of legend box<br> legsize: size of legend<br> cleg: color of legend box<br> legheight: height of legend box<br> pnote: position of note (default=1) (only numbers)<br> cbord: color of plot border (default= same cplot)<br> titlesize: size of title (default=20) (only numbers)<br> wordssize: size of words (default=12) (only numbers)<br> snote: size of note (default=11) (only numbers)<br> legpos: legend position (default= right)<br> legdir: legend direction (default=“horizontal”)<br> legcol: color of legend box<br> legspa: spacement in legend box<br> legvjust: vertical adjust in legend box<br> colors: colors of bars, need same number of correspondencies.<br>
<p>
<pre class="r"><code>randoms=data.frame(&quot;Period&quot;=letters[1:12],
            &quot;Values&quot;=c(2,6,4,-6,-2,1,-6,3,8,1,5,3))

p.col_ord_wl(randoms,randoms[[1]],randoms[[2]],title = &quot;Metools - p.col_ord_wl&quot;,xlab = NULL,ylab = NULL,legspa = 0.3,legvjust = -0.9,legsize = 12)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-45-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>p.col_wl</strong>
</h3>
<p>p.col_wl make a bar plot with legend.</p>
<p style="text-align:center;">
<strong>p.col_wl</strong>
<p>
<p style="text-align:center;">
data: a dataframe<br> xaxis: x axis data<br> yaxis: y axis data<br> ybreaks: number of y axis breaks (default=10)<br> percent: If TRUE y axis in percent (default=F)<br> yaccuracy: a round for y axis (default=0.01)<br> ydecimalmark: y decimal mark (default=“.”)<br> title: title of plot<br> xlab: x axis label<br> ylab: y axis label<br> stitle: subtitle<br> note: note<br> ctitles: color of titles (title,xlab,ylab)<br> cscales: color of the scales (default= same ctitles)<br> cbgrid: color of grid background<br> clgrid: color of grid lines<br> cplot: color of plot background<br> cserie: color of serie<br> cbserie: color of serie border (default= same cserie)<br> cticks: color of axis ticks<br> lwdserie: size of serie<br> legtitle: title of legend box<br> legsize: size of legend<br> cleg: color of legend box<br> legheight: height of legend box<br> pnote: position of note (default=1) (only numbers)<br> cbord: color of plot border (default= same cplot)<br> titlesize: size of title (default=20) (only numbers)<br> wordssize: size of words (default=12) (only numbers)<br> snote: size of note (default=11) (only numbers)<br> legpos: legend position (default= right)<br> legdir: legend direction (default=“horizontal”)<br> legcol: color of legend box<br> legspa: spacement in legend box<br> legvjust: vertical adjust in legend box<br> colors: colors of bars, need same number of correspondencies.<br>
<p>
<pre class="r"><code>randoms=data.frame(&quot;Period&quot;=letters[1:12],
            &quot;Values&quot;=c(2,6,4,-6,-2,1,-6,3,8,1,5,3))

p.col_wl(randoms,randoms[[1]],randoms[[2]],title = &quot;Metools - p.col_wl&quot;,xlab = NULL,ylab = NULL,legspa = 0.3,legvjust = -0.9,legsize = 12)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-46-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>In both p.col_wl and p.col_ord_wl we can change the colors of the bars, to do this just change the parameter colors. See an example below:</p>
<pre class="r"><code>randoms=data.frame(&quot;Period&quot;=letters[1:12],
            &quot;Values&quot;=c(2,6,4,-6,-2,1,-6,3,8,1,5,3))

p.col_wl(randoms,randoms[[1]],randoms[[2]],title = &quot;Metools - p.col_wl&quot;,xlab = NULL,ylab = NULL,note=&#39;The p.gradientcolor will be explained later&#39;,legspa = 0.3,legvjust = -0.9,legsize = 12,
         colors=p.gradientcolor(&#39;blue&#39;,&#39;red&#39;,12))</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-47-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>p.tscol</strong>
</h3>
<p>p.tscol make a bar plot in time serie format. The data don’t need be a ts object.</p>
<p style="text-align:center;">
<strong>p.tscol</strong>
<p>
<p style="text-align:center;">
data: a dataframe<br> xaxis: x axis data<br> yaxis: y axis data<br> dateformat: format of date in x axis (need a dataformat string) (default =“%Y-%m”)<br> datebreaks: datebreaks in x axis (default=“1 month”)<br> ybreaks: number of y axis breaks (default=10)<br> percent: If TRUE y axis in percent (default=F)<br> yaccuracy: a round for y axis (default=0.01)<br> ydecimalmark: y decimal mark (default=“.”)<br> title: title of plot<br> xlab: x axis label<br> ylab: y axis label<br> stitle: subtitle<br> note: note<br> ctitles: color of titles (title,xlab,ylab)<br> cscales: color of the scales (default= same ctitles)<br> cbgrid: color of grid background<br> clgrid: color of grid lines<br> cplot: color of plot background<br> cserie: color of serie<br> cbserie: color of serie border (default= same cserie)<br> cticks: color of axis ticks<br> lwdserie: size of serie<br> pnote: position of note (default=1) (only numbers)<br> cbord: color of plot border (default= same cplot)<br> titlesize: size of title (default=20) (only numbers)<br> wordssize: size of words (default=12) (only numbers)<br> snote: size of note (default=11) (only numbers)<br> xlim: limit of x axis (default=NULL)<br>
<p>
<pre class="r"><code>p.tscol(usagdp,as.Date(usagdp[[1]]),usagdp[[2]],title = &quot;Metools - p.tscol&quot;,xlab = NULL,ylab = NULL,datebreaks = &quot;1 year&quot;,dateformat=&quot;%Y&quot;)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-48-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>p.tscol probably will be the most used function of package, it will be further explored.<br> Are important pay attention in the xaxis parameter, the input don’t need be a ts object, but need be a vector in Date class. To certainly pass the correct class, you can use as.Date() in input of xaxis parameter. Other parameter to pay attention is the datebreaks, if i don’t set datebreaks equal 1 year in previous example, look the output:</p>
<pre class="r"><code>p.tscol(usagdp,as.Date(usagdp[[1]]),usagdp[[2]],title = &quot;Metools - p.tscol&quot;,xlab = NULL,ylab = NULL,dateformat=&quot;%Y&quot;)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-49-1.png" width="672" style="display: block; margin: auto;" /> This occurs because the default value of the parameter datebreaks is “1 month”, if the date column was in month it would have worked. So is important look at the date breaks of your data, and adjust correctly to datebreaks parameter.<br></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>p.tsl</strong>
</h3>
<p>p.tsl make a line plot in time serie format. The data don’t need be a ts object.</p>
<p style="text-align:center;">
<strong>p.tsl</strong>
<p>
<p style="text-align:center;">
data: a dataframe<br> xaxis: x axis data<br> yaxis: y axis data<br> dateformat: format of date in x axis (need a dataformat string) (default =“%Y-%m”)<br> datebreaks: datebreaks in x axis (default=“1 month”)<br> ybreaks: number of y axis breaks (default=10)<br> percent: If TRUE y axis in percent (default=F)<br> yaccuracy: a round for y axis (default=0.01)<br> ydecimalmark: y decimal mark (default=“.”)<br> title: title of plot<br> xlab: x axis label<br> ylab: y axis label<br> stitle: subtitle<br> note: note<br> ctitles: color of titles (title,xlab,ylab)<br> cscales: color of the scales (default= same ctitles)<br> cbgrid: color of grid background<br> clgrid: color of grid lines<br> cplot: color of plot background<br> cserie: color of serie<br> cticks: color of axis ticks<br> lwdserie: size of serie<br> pnote: position of note (default=1) (only numbers)<br> cbord: color of plot border (default= same cplot)<br> titlesize: size of title (default=20) (only numbers)<br> wordssize: size of words (default=12) (only numbers)<br> snote: size of note (default=11) (only numbers)<br> xlim: limit of x axis (default=NULL)<br>
<p>
<pre class="r"><code>p.tsl(usagdp,as.Date(usagdp[[1]]),usagdp[[2]],title = &quot;Metools - p.tsl&quot;,xlab = NULL,ylab = NULL,datebreaks = &quot;1 year&quot;,dateformat=&quot;%Y&quot;)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-50-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<p>At least we will see in sequence plot tools and multi plot functions. Plot tools have same prefix that plot functions (p.), they too have a utility without graphic but your main objective is offer support to metools plot functions.</p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>p.gradientcolor</strong>
</h3>
<p>p.gradientcolor is a function to make easy create gradient pallet. Recommended to color graphics created with metools p.functions.</p>
<p style="text-align:center;">
<strong>p.gradientcolor</strong>
<p>
<p style="text-align:center;">
color1: First gradient color<br> color2: Last gradient color<br> n: Number of colors<br>
<p>
<pre class="r"><code>p.gradientcolor(color1=&quot;white&quot;,color2=&quot;blue&quot;,n=10)</code></pre>
<pre><code>##  [1] &quot;#FFFFFF&quot; &quot;#E2E2FF&quot; &quot;#C6C6FF&quot; &quot;#AAAAFF&quot; &quot;#8D8DFF&quot; &quot;#7171FF&quot; &quot;#5555FF&quot;
##  [8] &quot;#3838FF&quot; &quot;#1C1CFF&quot; &quot;#0000FF&quot;</code></pre>
<p>Using in a metools graphic we have:</p>
<pre class="r"><code>p.col_wl(usagdp,format.Date(usagdp[[1]],format=&quot;%Y&quot;),usagdp[[2]],xlab=NULL,ylab=NULL,title = &quot;Metools - p.gradientcolor&quot;,colors = p.gradientcolor(color1=&quot;white&quot;,color2=&quot;blue&quot;,n=10),legspa = 0.25,legvjust = -1.1)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-52-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>p.seqdatebreaks</strong>
</h3>
<p>p.seqdatebreaks is a function to break a time axis from graphic in specific interval. This function are recommended to select time interval of graphics created with metools p.functions.</p>
<p style="text-align:center;">
<strong>p.seqdatebreaks</strong>
<p>
<p style="text-align:center;">
x: Time data from a Timeserie<br> periodicity: Time interval(string)<br>
<p>
<pre class="r"><code>p.seqdatebreaks(x = as.Date(usagdp[[1]]),periodicity = &quot;2 years&quot;)</code></pre>
<pre><code>## [1] &quot;2010-01-01&quot; &quot;2012-01-01&quot; &quot;2014-01-01&quot; &quot;2016-01-01&quot; &quot;2018-01-01&quot;</code></pre>
<p>This function is already used automatically when you set datebreaks parameters in plot functions.</p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>p.colorbypositive</strong>
</h3>
<p>p.colorbypositive is a function to create a vector with colors by positive or negative. Recommended to color graphics created with metools p.functions.</p>
<p style="text-align:center;">
<strong>p.colorbypositive</strong>
<p>
<p style="text-align:center;">
x: a numeric vector colorp: Positive values color (default=Green)<br> colorn: Negative values color (default=Red)<br>
<p>
<pre class="r"><code>v=c(-3,-2,2,-2,3,2)

p.colorbypositive(v)</code></pre>
<pre><code>## [1] &quot;#B21717&quot; &quot;#B21717&quot; &quot;#17B221&quot; &quot;#B21717&quot; &quot;#17B221&quot; &quot;#17B221&quot;</code></pre>
<p>Using in a metools graphic we have:</p>
<pre class="r"><code>randoms=data.frame(&quot;time&quot;=1:length(v),&quot;value&quot;=v)

p.col(randoms,randoms[[1]],randoms[[2]],title=&quot;Meplot - p.colorbypositive&quot;,ylab=NULL,xlab=NULL,cbserie=&#39;black&#39;,
      cserie=p.colorbypositive(v))</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-55-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>p.colorbyvar</strong>
</h3>
<p>p.colorbyvar is a function to create a vector with colors by variation. Recommended to color graphics created with metools p.functions.</p>
<p style="text-align:center;">
<strong>p.colorbyvar</strong>
<p>
<p style="text-align:center;">
x: a numeric vector colorp: Positive values color (default=Green)<br> colorn: Negative values color (default=Red)<br> lag: Lag to comparsion (default=1)
<p>
<pre class="r"><code>p.colorbyvar(v)</code></pre>
<pre><code>## [1] &quot;#B21717&quot; &quot;#17B221&quot; &quot;#17B221&quot; &quot;#B21717&quot; &quot;#17B221&quot; &quot;#B21717&quot;</code></pre>
<p>Using in a metools graphic we have:</p>
<pre class="r"><code>randoms=data.frame(&quot;time&quot;=1:length(v),&quot;value&quot;=v)

p.col(randoms,randoms[[1]],randoms[[2]],title=&quot;Meplot - p.colorbyvar&quot;,ylab=NULL,xlab=NULL,cbserie=&#39;black&#39;,
      cserie=p.colorbyvar(v))</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-57-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<p>Finally we have the multi plotting functions, these functions have mp. prefix and basically apply the parameters of the meplot plot functions to a ggplot graphic object. Use this functions to plot more one serie in a graph.</p>
<h3 style="font-size:22px;">
<strong>mp.s</strong>
</h3>
<p>mp.s make a plot with one or more series. The object parameter require a ggplot object (Look at the examples).</p>
<p style="text-align:center;">
<strong>mp.s</strong>
<p>
<p style="text-align:center;">
object: a ggplot graphic object<br> xaxis: one x axis of your graphics<br> yaxis: one y axis of your graphics<br> ybreaks: number of y axis breaks (default=10)<br> percent: If TRUE y axis in percent (default=F)<br> yaccuracy: a round for y axis (default=0.01)<br> ydecimalmark: y decimal mark (default=“.”)<br> title: title of plot<br> xlab: x axis label<br> ylab: y axis label<br> stitle: subtitle<br> note: note<br> ctitles: color of titles (title,xlab,ylab)<br> cscales: color of the scales (default= same ctitles)<br> cbgrid: color of grid background<br> clgrid: color of grid lines<br> cplot: color of plot background<br> cticks: color of axis ticks<br> pnote: position of note (default=1) (only numbers)<br> cbord: color of plot border (default= same cplot)<br> titlesize: size of title (default=20) (only numbers)<br> wordssize: size of words (default=12) (only numbers)<br> snote: size of note (default=11) (only numbers)<br> xlim: limit of x axis (default=NULL)<br>
<p>
<pre class="r"><code>randoms=data.frame(&quot;Period&quot;=letters[1:12],
            &quot;V1&quot;=c(2,6,4,-6,-2,1,-6,3,8,1,5,3),
            &quot;V2&quot;=c(4,2,-3,-5,-1,5,8,-2,7,3,5,3))

g=ggplot()+geom_line(aes(x=randoms[[1]],y=randoms[[2]],color=&#39;blue&#39;,group=1),lwd=1.5)+geom_line(aes(x=randoms[[1]],y=randoms[[3]],color=&#39;red&#39;,group=1),lwd=1.5)

mp.s(g,randoms[[1]],randoms[[3]],title=&quot;Metools - mp.s&quot;,xlab=NULL,ylab=NULL)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-58-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Other example:</p>
<pre class="r"><code>g=ggplot()+geom_col(aes(x=randoms[[1]],y=randoms[[2]],group=1),color=&#39;black&#39;,fill=&#39;black&#39;,lwd=1.5)+geom_line(aes(x=randoms[[1]],y=randoms[[3]],group=1),color=&#39;red&#39;,lwd=1.5)

mp.s(g,randoms[[1]],randoms[[3]],title=&quot;Metools - mp.s&quot;,xlab=NULL,ylab=NULL)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-59-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><br></p>
<h3 style="font-size:22px;">
<strong>mp.ts</strong>
</h3>
<p>mp.ts make plot in time serie format with one or more series. The data don’t need be a ts object. The object parameter require a ggplot object (Look at the examples).</p>
<p style="text-align:center;">
<strong>mp.ts</strong>
<p>
<p style="text-align:center;">
object: a ggplot graphic object<br> xaxis: one x axis of your graphics<br> yaxis: one y axis of your graphics<br> dateformat: format of date in x axis (need a dataformat string) (default =“%Y-%m”)<br> datebreaks: datebreaks in x axis (default=“1 month”)<br> ybreaks: number of y axis breaks (default=10)<br> percent: If TRUE y axis in percent (default=F)<br> yaccuracy: a round for y axis (default=0.01)<br> ydecimalmark: y decimal mark (default=“.”)<br> title: title of plot<br> xlab: x axis label<br> ylab: y axis label<br> stitle: subtitle<br> note: note<br> ctitles: color of titles (title,xlab,ylab)<br> cscales: color of the scales (default= same ctitles)<br> cbgrid: color of grid background<br> clgrid: color of grid lines<br> cplot: color of plot background<br> cticks: color of axis ticks<br> pnote: position of note (default=1) (only numbers)<br> cbord: color of plot border (default= same cplot)<br> titlesize: size of title (default=20) (only numbers)<br> wordssize: size of words (default=12) (only numbers)<br> snote: size of note (default=11) (only numbers)<br> xlim: limit of x axis (default=NULL)<br>
<p>
<pre class="r"><code>randoms=data.frame(&quot;Date&quot;=seq.Date(as.Date(&quot;2019-01-01&quot;),as.Date(&quot;2019-12-01&quot;),by=&#39;month&#39;),
            &quot;V1&quot;=c(2,6,4,-6,-2,1,-6,3,8,1,5,3),
            &quot;V2&quot;=c(4,2,-3,-5,-1,5,8,-2,7,3,5,3))

g=ggplot()+geom_line(aes(x=randoms[[1]],y=randoms[[2]],color=&#39;blue&#39;,group=1),lwd=1.5)+geom_line(aes(x=randoms[[1]],y=randoms[[3]],color=&#39;red&#39;,group=1),lwd=1.5)

mp.ts(g,randoms[[1]],randoms[[3]],title=&quot;Metools - mp.ts&quot;,xlab=NULL,ylab=NULL,dateformat=&quot;%m/%y&quot;)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-60-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>You can use too the multiplot functions to have more types of graphics, the area graph is an example:</p>
<pre class="r"><code>randoms=data.frame(&quot;Date&quot;=seq.Date(as.Date(&quot;2019-01-01&quot;),as.Date(&quot;2019-12-01&quot;),by=&#39;month&#39;),
            &quot;V&quot;=c(2,4,6,3,5,8,6,3,5,4,5,6))

g=ggplot()+geom_area(aes(x=randoms[[1]],y=randoms[[2]],group=1),color=&#39;blue&#39;,fill=&#39;blue&#39;,lwd=1.5)

mp.ts(g,randoms[[1]],randoms[[3]],title=&quot;Metools - mp.ts&quot;,xlab=NULL,ylab=NULL,dateformat = &quot;%b&quot;)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-61-1.png" width="672" style="display: block; margin: auto;" /></p>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
